// Package api configures an http server for administration and application resources.

package router

import (
	"fmt"
	"net/url"
	"os"

	swagger "github.com/swaggo/http-swagger"

	"github.com/agent-auth/agent-auth-api/pkg/authz"
	_ "github.com/agent-auth/agent-auth-api/web/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/agent-auth/agent-auth-api/web/services/health"
	"github.com/agent-auth/agent-auth-api/web/services/v1/resourceservice"
	"github.com/go-chi/chi"
)

type router struct {
	health          health.Health
	resourceService resourceservice.ResourceService
	tokenProvider   authz.TokenProvider
}

// NewRouter returns the router implementation
func NewRouter() Router {
	// Validate required environment variables
	requiredEnvVars := map[string]string{
		"KEYCLOAK_URL":      os.Getenv("KEYCLOAK_URL"),
		"KEYCLOAK_TOKEN":    os.Getenv("KEYCLOAK_TOKEN"),
		"API_AUTH_JWKS_URL": os.Getenv("API_AUTH_JWKS_URL"),
	}

	// Check for missing required variables
	for name, value := range requiredEnvVars {
		if value == "" {
			panic(fmt.Sprintf("%s is required", name))
		}
	}

	// Validate URL format for relevant variables
	urlVars := map[string]string{
		"KEYCLOAK_URL":      requiredEnvVars["KEYCLOAK_URL"],
		"API_AUTH_JWKS_URL": requiredEnvVars["API_AUTH_JWKS_URL"],
	}

	for name, value := range urlVars {
		if _, err := url.Parse(value); err != nil {
			panic(fmt.Sprintf("%s is invalid: %v", name, err))
		}
	}

	svc, err := resourceservice.NewResourceService(
		requiredEnvVars["KEYCLOAK_URL"],
		requiredEnvVars["KEYCLOAK_TOKEN"],
	)
	if err != nil {
		panic(fmt.Sprintf("failed to create resource service: %v", err))
	}

	return &router{
		health:          health.NewHealth(),
		resourceService: svc,
		tokenProvider: *authz.NewTokenProvider(
			requiredEnvVars["API_AUTH_JWKS_URL"],
		),
	}
}

// Router configures application resources and routes.
func (router *router) Router(enableCORS bool) *chi.Mux {
	r := chi.NewRouter()

	// use CORS middleware if client is not served by this api, e.g. from other domain or CDN
	if enableCORS {
		r.Use(corsConfig().Handler)
	}

	// =================  health routes ======================
	r.Get("/health", router.health.GetHealth)

	// ================= API Documentation ====================
	r.Get("/swagger/*", swagger.Handler())

	protected := chi.NewRouter()
	protected.Use(authz.AuthMiddleware(
		&router.tokenProvider,
		os.Getenv("API_AUTH_AUDIENCE"),
		os.Getenv("API_AUTH_ISSUER"),
	))

	// Base API path for all resource operations
	protected.Route("/{workspace_id}/{project_id}/oauth/resources", func(r chi.Router) {
		// System Admin routes

		// Workspace Admin routes
		r.With(authz.RequireRoles(authz.WorkspaceAdmin, authz.SystemAdmin, authz.AppAdmin, authz.AppDeveloper)).
			Group(func(r chi.Router) {
				r.Post("/", router.resourceService.Create)
				r.Put("/{resource_id}", router.resourceService.Update)
				r.Delete("/{resource_id}", router.resourceService.Delete)
			})

		// Viewer routes (and above)
		r.With(authz.RequireRoles(
			authz.AppViewer,
			authz.AppDeveloper,
			authz.AppAdmin,
			authz.WorkspaceAdmin,
			authz.SystemAdmin,
		)).Group(func(r chi.Router) {
			r.Get("/", router.resourceService.List)
			r.Get("/{resource_id}", router.resourceService.Get)
		})
	})

	// Scoped routes can be added similarly if needed
	r.Mount("/", protected)
	return r
}
